### ISSUE TITLE
有的头文件缺失

### ISSUE THREAD

**Issue by leebyee** [BluewhaleRobot/roscppExample#1]
今天下载工程编译，发现报错：
![image](https://user-images.githubusercontent.com/47856151/60149448-4fa64300-9807-11e9-931c-f0f8a2765b01.png)
看了一下文件目录，工程里面确实没有这几个文件，请问这些文件能不能传上来？是不是在.gitignore里面注释掉了呀？
辛苦了，谢谢~

**Comment by leebyee** [comment]
我自己解决了，谢谢~

**Comment by dmitterberger** [comment]
> I downloaded the project compilation today and found an error: I looked at the file directory, and there are indeed no files in the project. Can these files be uploaded? Is it commented out in .gitignore? Thank you~
> ![image](https://user-images.githubusercontent.com/47856151/60149448-4fa64300-9807-11e9-931c-f0f8a2765b01.png)

I have the same issue - is there any way to upload these files?
