### ISSUE TITLE
missing roscpp.lib file

### ISSUE THREAD

**Issue by dmitterberger** [BluewhaleRobot/roscppExample#2]
Hi,

I tried running the roscppExample file in VS2017 but get this error:
![image](https://user-images.githubusercontent.com/43745493/99518774-5354df80-2991-11eb-870d-3e7e071a8f3b.png)

with a closer look, I really can not find the .lib file. Could you pinpoint me to the location? There were also some other files missing but I found them within the boost folder.

**Comment by randoms** [comment]
Yes, I have made a mistake, these libs are in my gitignore list, and I forgot to add them. I have uploaded the libs and you can have a try now.

**Comment by dmitterberger** [comment]
thanks a lot, it works now!
